### ISSUE TITLE
Does not follow my previous package.json indentation

### ISSUE THREAD

**Issue by patarapolw** [RocktimSaikia/syzer#1]
I normally indent `package.json` with 2 spaces.

But that shouldn't matter. `syzer` should not change indentation, or even json key ordering itself. (If I need to reorder, I normally use [`sort-package-json`](https://github.com/keithamus/sort-package-json).)

**Comment by rocktimsaikia** [comment]
@patarapolw thanks for pointing out. I did have this in mind while working on syzer initially. Since it was totally a personal project made public there is still much room for improvement. I will look into the issue soon but in the meantime, if you are interested in assigning this issue to yourself and contribute, let me know. That's hugely appreciated. Currently, this project needs all sorts of contributions.

**Comment by rocktimsaikia** [comment]
@patarapolw This issue is fixed in the latest commit ([#1](https://github.com/RocktimSaikia/syzer/pull/2)). Please update syzer to the latest version.
